PUB_KEY_PATH = "~/.ssh/id_rsa.pub"
PUB_KEY_PATH_DEST = "~/.ssh/authorized_keys"
SSH_CONF_PATH = "~/.ssh/config"
IMAGE_BOX = "zuwarskej/debian-10"
VM_PROVIDER = "virtualbox"
N = 2

Vagrant.configure("2") do |config|
    (1..N).each do |i|                                                                              # Loop for VMs
        config.ssh.forward_agent = true                                                             # SSH Forwarding
        config.ssh.insert_key = false                                                               # Use One SSH key fo all VMs
        config.vagrant.plugins = ["vagrant-hostmanager"]                                            # Enabled plugins
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.ignore_private_ip = false
        config.hostmanager.include_offline = true
        config.vm.define "node-#{i}" do |node|                                                      # Box Settings
            node.vm.box = IMAGE_BOX
            node.vm.hostname = "node-#{i}"
            node.vm.box_check_update = false
            node.vm.provider VM_PROVIDER do |v|                                                     # Provider Settings
                v.name = "node-#{i}"
                v.gui = false
                v.memory = 512
                v.cpus = 1
            end
            node.vm.synced_folder ".", "/vagrant"                                                   # Shared Folder settings
            node.vm.network :private_network, ip: "172.16.10.#{1+i}"                                # Network Settings
            node.vm.provision :file, source: PUB_KEY_PATH, destination: PUB_KEY_PATH_DEST           # Provision Settings
            node.vm.provision :file, source: "config", destination: SSH_CONF_PATH
            node.vm.provision :shell, inline: "apt-get update >/dev/null 2>&1"
            node.vm.provision :shell, path: "github.sh"
        config.vm.provision :hostmanager
        end
    end
end